spring.application.name=bibliotech

spring.datasource.url=jdbc:h2:mem:bibliotechdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

jwt.secret=R0hKV0h4Y2V3QjN4Vm1xQ01MSHJmQTRVS0JzM2xBZ0xPZG1IWVp1Y2VMQQ==
jwt.expiration=86400000

# Activate this profile when running MongoDB reactive endpoints.
# spring.profiles.active=mongo
# spring.data.mongodb.uri=mongodb://localhost:27017/bibliotech
